name: InfoGuide
main: net.dockter.sguide.Main
authors: [Dockter, ZNickq]
version: 1.5
commands:
  infoguide:
    description: InfoGuide command.
    aliases: sguide
    usage: /infoguide [player]
    permission: infoguide.view
    permissions-message: You don't have <permission>
permissions:
    infoguide.*:
        description: Gives access to all infoguide abilities
        children:
            infoguide.view: true
            infoguide.delete: true
            infoguide.create: true
            infoguide.edit: true
            infoguide.admin: true
            infoguide.bypass: true
    infoguide.view:
        description: Allows users to be able to view guides
        default: true
    infoguide.delete:
        description: Allows user to delete guides
        default: op
    infoguide.create:
        description: Allows user to create new guides.
        default: op
    infoguide.edit:
        description: Allows users to modify existing guides.
        default: op
    infoguide.admin:
        description: Allows users access to all functionalities.
        default: op
    infoguide.bypass:
        description: Allows users to bypass InfoGuide on Login.
        default: op
    infoguide.bypassall:
        description: Allows Administrators to force bypass for specific user/groups
        default: op        